/**
 * FinWise AI — Legal content
 * Centralised disclaimers, warnings, and terms. Update TERMS_VERSION on any change.
 */

export const TERMS_VERSION = "1.0";
export const COMPANY_NAME = "FinWise AI";
export const SITE_DOMAIN = "finwiseai-advisor.com";

// Short disclaimer shown on every advice screen
export const SHORT_DISCLAIMER =
  "FinWise AI provides general financial information and educational guidance only — not personal financial, tax, investment, or legal advice. We are not a licensed financial adviser. Verify all information with a registered professional before acting. We accept no liability for any loss arising from use of this tool.";

// Country-specific regulatory warnings
export const GENERAL_ADVICE_WARNING: Record<string, string> = {
  AU:
    "General Advice Warning (Australia): This information is general in nature and does not take into account your personal objectives, financial situation or needs. It is not personal financial product advice and FinWise AI does not hold an Australian Financial Services Licence (AFSL). Before acting, consider its appropriateness and consult a licensed financial adviser, registered tax agent, or accountant. Tax information is general and not a substitute for advice from a registered tax agent.",
  NZ:
    "General Information Notice (New Zealand): This is general information only and not regulated financial advice under the Financial Markets Conduct Act 2013. FinWise AI is not a licensed Financial Advice Provider (FAP). Consult a licensed financial adviser or chartered accountant, and refer to Inland Revenue (IRD) for tax matters, before making decisions.",
  CA:
    "Disclaimer (Canada): This information is general and educational only, not personalized investment, tax, or financial advice. FinWise AI is not a registered investment adviser or dealer. Consult a licensed financial advisor, CPA, or the Canada Revenue Agency (CRA) before acting.",
  US:
    "Disclaimer (United States): This information is general and educational only and does not constitute investment, tax, or financial advice. FinWise AI is not a registered investment adviser (RIA) or broker-dealer. Consult a licensed financial advisor, CPA, or the IRS before making financial decisions.",
};

export function getAdviceWarning(country?: string): string {
  return GENERAL_ADVICE_WARNING[country || "AU"] || GENERAL_ADVICE_WARNING.AU;
}

// Full disclaimer page content
export const DISCLAIMER_SECTIONS = [
  {
    title: "1. Information Only — Not Advice",
    body:
      "FinWise AI is an educational and informational tool. All content, calculations, projections, and AI-generated responses are general in nature and provided for informational purposes only. Nothing on this platform constitutes personal financial advice, tax advice, investment advice, legal advice, accounting advice, or a recommendation to buy, sell, or hold any financial product or security.",
  },
  {
    title: "2. No Licensed Adviser Relationship",
    body:
      "FinWise AI does not hold an Australian Financial Services Licence (AFSL), is not a licensed Financial Advice Provider in New Zealand, is not a registered investment adviser in Canada or the United States, and is not a registered tax agent or accountant in any jurisdiction. Using this platform does not create any adviser-client, fiduciary, or professional relationship.",
  },
  {
    title: "3. AI-Generated Content May Contain Errors",
    body:
      "Responses are generated by artificial intelligence and may be inaccurate, incomplete, or out of date. Tax rules, contribution caps, interest rates, and thresholds change frequently. You must independently verify all information with a qualified, registered professional and the relevant authority (ATO, IRD, CRA, IRS) before relying on it.",
  },
  {
    title: "4. No Liability for Loss",
    body:
      "To the maximum extent permitted by law, FinWise AI, its owners, operators, employees, and contributors accept no responsibility or liability for any loss, damage, cost, or expense (including direct, indirect, incidental, consequential, or financial loss) arising from or in connection with your use of, or reliance on, this platform or any information it provides. You use this tool entirely at your own risk.",
  },
  {
    title: "5. Your Responsibility",
    body:
      "You are solely responsible for your financial decisions. Before making any financial, tax, investment, or borrowing decision, obtain personal advice from an appropriately licensed and registered professional who can consider your full circumstances. Past performance is not indicative of future results. Projections are estimates only and not guarantees.",
  },
  {
    title: "6. Not a Substitute for Professional Advice",
    body:
      "This tool does not replace advice from a licensed financial adviser, registered tax agent, accountant, mortgage broker, or lawyer. For complex matters — including tax returns, investment strategy, estate planning, and major borrowing — always engage a qualified professional.",
  },
  {
    title: "7. Data Accuracy",
    body:
      "Information you enter or upload (including extracted document data) may be processed by AI and may contain extraction errors. Always review auto-filled figures for accuracy before relying on them.",
  },
];

export const PRIVACY_SECTIONS = [
  {
    title: "1. Information We Collect",
    body:
      "We collect the account information you provide (name, email), the financial details you enter, and documents you upload. Documents are processed to extract financial data and stored securely in your private account.",
  },
  {
    title: "2. How We Use Your Information",
    body:
      "Your information is used solely to provide the service — generating guidance, calculations, and projections personalised to you. We do not sell your personal information to third parties.",
  },
  {
    title: "3. Data Security",
    body:
      "Data is encrypted in transit (TLS 1.3) and at rest (AES-256). Access is protected by row-level security so only you can access your data. We follow industry-standard security practices and our infrastructure providers maintain SOC 2 certification.",
  },
  {
    title: "4. AI Processing",
    body:
      "To generate responses, the financial context and questions you submit are processed by AI language models. We use providers that do not train their public models on your submitted data via API.",
  },
  {
    title: "5. Your Rights",
    body:
      "Consistent with the Privacy Act 1988 (AU), Privacy Act 2020 (NZ), PIPEDA (CA), and CCPA (US), you may request access to, correction of, or deletion of your personal data at any time by contacting us or deleting your account.",
  },
  {
    title: "6. Data Retention",
    body:
      "We retain your data while your account is active. On account deletion, your personal data and documents are removed from our systems.",
  },
];
